### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by leifjohn** [JeremyEnglert/JointsWP-Documentation#22]
I have been at this for days but cannot get this to install. 

leifjohn@leif-pop-os:~/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP$ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated flatten@1.0.2: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated browserslist@0.4.0: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated chokidar@2.0.4: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated phantom@4.0.12: This package is no longer maintained
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.1: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated axios@0.17.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.5.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated unicode-5.2.0@0.7.5: Use @unicode/unicode-5.2.0 instead.
npm ERR! code 1
npm ERR! path /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /home/leifjohn/.nvm/versions/node/v20.11.1/bin/node /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/leifjohn/.nvm/versions/node/v20.11.1/bin/node',
npm ERR! gyp verb cli   '/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.11.1 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:201:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:201:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 20.11.1
npm ERR! gyp verb command install [ '20.11.1' ]
npm ERR! gyp verb install input version string "20.11.1"
npm ERR! gyp verb install installing version: 20.11.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 20.11.1
npm ERR! gyp verb build dir attempting to create "build" dir: /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/leifjohn/.node-gyp/20.11.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/leifjohn/.node-gyp/20.11.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/leifjohn/.node-gyp/20.11.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
npm ERR!     params['parallel'], params['root_targets'])
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
npm ERR!     variables, includes, depth, check, True)
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
npm ERR!     includes, True, check)
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
npm ERR!     aux_data, includes, check)
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
npm ERR!     LoadOneBuildFile(include, data, aux_data, None, False, check),
npm ERR!   File "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
npm ERR!     None)
npm ERR!   File "/home/leifjohn/.node-gyp/20.11.1/include/node/common.gypi", line 1
npm ERR!     incremental linking
npm ERR!                       ^
npm ERR! SyntaxError: invalid syntax
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 6.6.10-76060610-generic
npm ERR! gyp ERR! command "/home/leifjohn/.nvm/versions/node/v20.11.1/bin/node" "/home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/leifjohn/vvv-local/www/3rivers/public_html/wp-content/themes/JointsWP/node_modules/node-sass
npm ERR! gyp ERR! node -v v20.11.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

**Comment by legiondesigns** [comment]
This theme is no longer maintain or updated. It is now considered defunked. Author hasn't updated it in 6 years.
